### ISSUE TITLE
GitHub Terms of Service violation

### ISSUE THREAD

**Issue by rokoucha** [gamesukimanIRS/ServerBackUp#1]
このリポジトリに適用されているライセンスは[GitHub Terms of Service](https://help.github.com/articles/github-terms-of-service/)に違反しています。

>By setting your repositories to be viewed publicly, you agree to allow others to view and "fork" your repositories (this means that others may make their own copies of Content from your repositories in repositories they control).
>https://help.github.com/articles/github-terms-of-service/#5-license-grant-to-other-users

あなたがもし、現在適用されているライセンスを今後も継続して適用するにはプライベートリポジトリに変更する必要があります。

**Comment by gamesukimanIRS** [comment]
コードの無断コピー、無断転載に関する記載をライセンスから削除しました。
